from python:3.11

WORKDIR /app

COPY requirements.txt ./

RUN pip install --no-cache-dir -r requirements.txt
RUN pip install flask gunicorn
COPY engine.py ./
COPY server.py ./

CMD ["gunicorn", "-b", "0.0.0.0:5433", "server:app"]
